// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NooshRewardsApi.Data;

#nullable disable

namespace NooshRewardsApi.Migrations
{
    [DbContext(typeof(RewardsDbContext))]
    [Migration("20260817095950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("NooshRewardsApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.PunchCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPunches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RewardRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesRedeemed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RewardRuleId");

                    b.HasIndex("CustomerId", "RewardRuleId")
                        .IsUnique();

                    b.ToTable("PunchCards");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.PunchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PunchCardId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PunchCardId");

                    b.ToTable("PunchLogs");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.ReceiptSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RewardRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RewardRuleId");

                    b.HasIndex("ReceiptReference", "AmountPaid", "PurchaseDate")
                        .IsUnique();

                    b.ToTable("ReceiptSubmissions");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.RewardRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredPunches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RewardRules");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.ScanToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RewardRuleId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ScanTokens");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.PunchCard", b =>
                {
                    b.HasOne("NooshRewardsApi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NooshRewardsApi.Models.RewardRule", "RewardRule")
                        .WithMany()
                        .HasForeignKey("RewardRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RewardRule");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.PunchLog", b =>
                {
                    b.HasOne("NooshRewardsApi.Models.PunchCard", "PunchCard")
                        .WithMany()
                        .HasForeignKey("PunchCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PunchCard");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.ReceiptSubmission", b =>
                {
                    b.HasOne("NooshRewardsApi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NooshRewardsApi.Models.RewardRule", "RewardRule")
                        .WithMany()
                        .HasForeignKey("RewardRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RewardRule");
                });

            modelBuilder.Entity("NooshRewardsApi.Models.ScanToken", b =>
                {
                    b.HasOne("NooshRewardsApi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NooshRewardsApi.Models.RewardRule", "RewardRule")
                        .WithMany()
                        .HasForeignKey("RewardRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RewardRule");
                });
#pragma warning restore 612, 618
        }
    }
}
